name: GitOps CI

on:
  push:
    branches: [ main ]

jobs:
  update-manifests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update deployment.yaml with new image tag
      run: |
        echo "Patching nginx image in deployment.yaml..."
        sed -i 's|nginx:1.25|nginx:1.25-alpine|' k8s/deployment.yaml

    - name: Commit and push manifest changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "ci@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/iracic82/my-nginx-demo.git
        
        echo "🧪 Confirming remote config:"
        git remote -v

        git add k8s/deployment.yaml
        git commit -m "CI: update nginx image tag" || echo "No changes"
        git push origin main
